// Brand-kit packaging. Assembles generated artefacts into a single organized
// .zip with a manifest, README, and a conventional folder tree. The zip is the
// product. fflate is tiny, fast, and dependency-free, and runs in the Node
// serverless runtime. Kept decoupled from the other packages: callers pass
// already-serialized content, so the exporter has no upstream type coupling.

import { strToU8, zipSync } from "fflate";

export interface KitLogo {
  filename: string;
  label: string;
  svg: string;
}

export interface KitName {
  term: string;
  strategy: string;
  note: string;
  composite: number;
}

export interface KitSwatch {
  role: string;
  hex: string;
  oklch: string;
}

/** A server-authorized persisted derivative to include in the kit. */
export interface KitGeneratedAsset {
  path: string;
  bytes: Uint8Array;
}

export interface BrandKitInput {
  brandName: string;
  slug: string;
  generatedAt: string;
  logos: KitLogo[];
  faviconSvg: string;
  webManifest: unknown;
  headSnippet: string;
  tokensJson: unknown;
  tokensCss: string;
  names: KitName[];
  palette: KitSwatch[];
  generatedAssets?: KitGeneratedAsset[];
}

export interface BrandKitManifest {
  brand: string;
  slug: string;
  generatedAt: string;
  generator: string;
  files: string[];
}

export interface BrandKitOutput {
  filename: string;
  bytes: Uint8Array;
  manifest: BrandKitManifest;
}

const GENERATOR = "Etymalia";

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function readme(input: BrandKitInput): string {
  const swatches = input.palette
    .map((swatch) => `- **${swatch.role}** — \`${swatch.hex}\` (${swatch.oklch})`)
    .join("\n");
  const names = input.names.length
    ? input.names.map((name) => `- **${name.term}** — ${name.note}`).join("\n")
    : "- (no names shortlisted)";

  return [
    `# ${input.brandName} — Brand Kit`,
    "",
    `Generated by ${GENERATOR} on ${input.generatedAt}.`,
    "",
    "## Contents",
    "",
    "- `logo/` — SVG logo variants (full colour and single-colour `currentColor`).",
    "- `favicon/` — SVG favicon, web manifest, and the `<head>` snippet.",
    "- `tokens/` — DTCG design tokens (`tokens.json`) and CSS custom properties (`tokens.css`).",
    "- `names/` — shortlisted name candidates with provenance.",
    "- `palette/` — colour swatches with HEX and OKLCH values.",
    ...(input.generatedAssets?.length ? ["- `social/` — rendered platform-ready social assets."] : []),
    "",
    "## Palette",
    "",
    swatches,
    "",
    "## Names",
    "",
    names,
    "",
    "## Using the favicon",
    "",
    "Copy the contents of `favicon/head.html` into your site's `<head>`, and serve",
    "`favicon.svg` and `site.webmanifest` from your web root.",
    "",
    "## Single-colour logos",
    "",
    "The `*-mono` SVGs use `currentColor`. Set the surrounding element's CSS",
    "`color` to recolour them — no re-export needed for black, white, or inverted",
    "lockups.",
    "",
  ].join("\n");
}

/** Build the organized brand-kit zip. Returns bytes plus the manifest. */
export function buildBrandKit(input: BrandKitInput): BrandKitOutput {
  const files: Record<string, Uint8Array> = {};

  for (const logo of input.logos) {
    files[`logo/${logo.filename}`] = strToU8(logo.svg);
  }
  files["favicon/favicon.svg"] = strToU8(input.faviconSvg);
  files["favicon/site.webmanifest"] = strToU8(json(input.webManifest));
  files["favicon/head.html"] = strToU8(input.headSnippet);
  files["tokens/tokens.json"] = strToU8(json(input.tokensJson));
  files["tokens/tokens.css"] = strToU8(input.tokensCss);
  files["names/names.json"] = strToU8(json(input.names));
  files["palette/palette.json"] = strToU8(json(input.palette));
  for (const asset of input.generatedAssets ?? []) {
    const path = safeGeneratedAssetPath(asset.path);
    if (path) files[path] = asset.bytes;
  }
  files["README.md"] = strToU8(readme(input));

  const manifest: BrandKitManifest = {
    brand: input.brandName,
    slug: input.slug,
    generatedAt: input.generatedAt,
    generator: GENERATOR,
    files: Object.keys(files).sort(),
  };
  files["manifest.json"] = strToU8(json(manifest));

  const bytes = zipSync(files, { level: 6 });
  return { filename: `${input.slug || "brand"}-kit.zip`, bytes, manifest };
}

function safeGeneratedAssetPath(path: string): string | null {
  const filename = path.split("/").at(-1);
  if (!filename || !/^[a-z0-9][a-z0-9._-]*$/i.test(filename)) return null;
  return `social/${filename}`;
}
